### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by KarelWintersky**
Exclude whole directories.

### CODE REVIEW

**Comment by KarelWintersky** [comment]
With `bin/` directory content not exluded while 
```
composer require rmccue/requests
```

**Comment by jrfnl** [comment]
@KarelWintersky That's because the `.gitattributes` files was only recently added and is not contained in a released version yet.

The file as it is, should work fine. Suggest: close.

**Comment by KarelWintersky** [comment]
> on 28 Aug 2018
Recently??? Really? :)

Well, please, make new release version.

**Comment by rmccue** [comment]
There'll be a new release when we're ready for a new one. :)

**Comment by KarelWintersky** [comment]
Estimated waiting time?

**Comment by rmccue** [comment]
When it's ready. :)

**Comment by KarelWintersky** [comment]
I.e. NEVER.

Thanx.

**Comment by jrfnl** [comment]
@KarelWintersky No need to be so pessimistic. While I agree that the PR was open for way too long, it only got merged 5 days ago, so that's pretty _recently_.

**Comment by KarelWintersky** [comment]
I don't want use dev-master dependancy in my project. Only fixed version.

**Comment by jrfnl** [comment]
@KarelWintersky We're working on it ;-)

**Pull request closed without merging**
