### PR TITLE
Update cacert.pem to latest version (2020-01-01)

### LINKED ISSUE #384: CA Bundle is out of date
[The certificate authority bundle](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cacert.pem) is out of date (last updated in 2012) and causes errors when connecting to services with newer certificates, as discussed in PRs #212, #330, #333 and #376.

### PR DESCRIPTION
**Pull request by patmead**
File sourced from https://curl.haxx.se/docs/caextract.html

Fixes #384

### CODE REVIEW

**Comment by patmead** [comment]
This update does cause an error in the PHP 5.3 test script, but I hope that's an acceptable compromise given that:

- [PHP 5.3 officially reached end-of-life in 2014](https://www.php.net/eol.php), and
- PHP 5.3 users may still work around that issue by specifying a different ca-bundle [as outlined in this project's documentation](https://github.com/rmccue/Requests/blob/master/docs/usage-advanced.md#secure-requests-with-ssl) 

(As an aside, that same document claims that "HTTPS requests will use the most secure options available" so hopefully this PR will bring us in line with that ;) )

**Comment by ozh** [comment]
Tests are flaky and easily timeout. I've triggered the build again and 5.3 pass, so I assume everything is fine with your PR

**Comment by ozh** [comment]
@rmccue we would really need you to ease the check status requirement to allow merging in such a situation

**Comment by patmead** [comment]
@rmccue Could you hit the Merge button on this approved PR? If there's anything blocking this from being merged please let me know!

**Comment by jrfnl** [comment]
The previous PRs for this - #212, #330 and #333 contained discussion about adjustments made to the certificate for compatibility. I'm not sure those adjustments were made in this PR which has now been merged. It might be a good idea for someone who involved to have a critical look if another update is needed to this before a release.

**Pull request merged**
