### PR TITLE
cURL: Support custom HTTP methods

### PR DESCRIPTION
**Pull request by ocean90**
See https://core.trac.wordpress.org/ticket/37503 for background.

The test doesn't work (yet) because there is no /purge endpoint.

### CODE REVIEW

**Comment by rmccue** [comment]
https://github.com/RequestsPHP/test-server is the source for the test server. :)

**Comment by ocean90** [comment]
@rmccue No idea why it returns a 501 error. :(

**Comment by ocean90** [comment]
Instead of adding a new case we can also combine the default case with PATCH, PUT, DELETE and OPTIONS. See https://core.trac.wordpress.org/attachment/ticket/37503/37503.2.patch.

@rmccue Let me know if this is a better approach, happy to refresh the PR. (It would also fix the coverage thing. :))

**Comment by rmccue** [comment]
Coverage can be pretty safely ignored for <0.1%; I tried this PR locally and it worked, but not on Travis, so need to get to the bottom of that. Haven't had time yet, alas.

I'd prefer the switch be explicit in what it supports, but `case ...: default:` is fine to avoid the duplication and still be explicit.

**Comment by rmccue** [comment]
Tests passing, wunderbar!

**Pull request merged**
