### PR TITLE
Updated the outdated cacert.pem file used for certificate verification.

### PR DESCRIPTION
**Pull request by donoskaro**
Old cacert.pem file can cause SSL verification errors such as with MailGun's API.

### CODE REVIEW

**Comment by soulseekah** [comment]
Good luck here. We've been waiting for an update for over 2 years now: https://github.com/rmccue/Requests/pull/212

**Comment by rmccue** [comment]
Sorry about the delay here folks. The compatibility of certificates was the main concern with this, but we're now significantly out-of-date, so we should work on that as a secondary priority instead.

@soulseekah I'll defer to your testing on #212; should we merge this PR and close #212 or vice versa?

**Comment by soulseekah** [comment]
I'll update https://github.com/soulseekah/libssl-cacert-tests with the latest cacert.pem, add more libssl versions and we can probably merge this one as #212 has 2 out of date pem files.

Stay tuned and thanks @rmccue

**Comment by soulseekah** [comment]
My tests are erroring on openssl-0.9.8e with api.mailchimp.com certificates.

```
backends/openssl-common.sh: line 16:  5429 Illegal instruction     (core dumped) LD_LIBRARY_PATH=. ./apps/openssl verify -verbose -x509_strict -CAfile ../$1 -CApath /tmp/ ../$2
[ERR] openssl-0.9.8e cacerts/curl-201180620.pem certs/api.mailchimp.com.pem
```

Can't reproduce locally, it may be a TravisCI issue, I'll try a different distribution perhaps. Here are local results for 0.9.8e:

image

The rest are fine. Including tests on openssl-1.1.1 https://travis-ci.org/soulseekah/libssl-cacert-tests/builds/430076702

**Comment by donoskaro** [comment]
@soulseekah I have also run my own tests on this and only got failureswith 0.9.8e (and none with f and j).
Could this be due to lack of support for SNI in 0.9.8e?

**Comment by soulseekah** [comment]
@donoskaro what are your system specs? Did you also get segfaults and illegal instructions?

**Comment by donoskaro** [comment]
@soulseekah I am using a modified version of your test setup ([soulseekah/libssl-cacert-tests](https://github.com/soulseekah/libssl-cacert-tests)) running on Travis (debian).

Please see [here](https://travis-ci.org/donoskaro/cacert-test/builds/431609919) for the latest build results, there are more combinations to see more easily what is going on, you will notice that starting from 0.9.8f builds are passing. The source is available [here](https://github.com/donoskaro/cacert-test). Also, there is a failure for requests-php-60db37.pem & 1.0.1e, but that is due to the age of the certificate (domain: api.mailgun.net which was my original issue).

I have also added an extra set of certificates to test, a list of websites can be located here: https://gist.github.com/donoskaro/371aea2bdca95a0307320cfac89c477e.

**Comment by soulseekah** [comment]
So 0.9.8e is failing even with the current/old cacert.pem file on Travis either way.

Thanks for confirming. Any other thoughts before we ping the maintainer?

**Comment by donoskaro** [comment]
Just wanted to point out that the reason that e is failing is the that we are testing it against "new" certificates.

The cacert.pam file should definitely be updated as soon as possible as support for SSL certificates will continue to decrease. I have tried playing around with the order of the certificates as well as placing the 1024 bit roots back into the file (similiar to what has been suggested in #212) however, I had no luck with that.

My only solution would be to drop support for e and go for the next version (f) however I am not sure of how many people are still using the former.

**Comment by soulseekah** [comment]
My tests check the old cacert.pam file from WordPress and that's still failing on e, so the update doesn't make things any worse for builds where e is failing. I vote to merge, if my vote means anything.

**Comment by donoskaro** [comment]
Any update on this? @rmccue

**Comment by jrfnl** [comment]
Closing as fixed by #385. @soulseekah would you be willing/able to test the current `master` to see if things are okay now ?

**Comment by soulseekah** [comment]
Latest version is October 14th 2020. There may have been some CAs that have been removed as rogue. It's important to keep the file updated as revocations should propagate as soon as possible.

These CAs were removed since the beginning of the year for various reasons.

- Verisign Class 3 Public Primary Certification Authority - G3
- AddTrust External Root
- Taiwan GRCA
- OISTE WISeKey Global Root GA CA
- Staat der Nederlanden Root CA - G2
- EE Certification Centre Root CA
- LuxTrust Global Root 2

I would strongly recommend fetching the latest version before release from https://curl.haxx.se/ca/cacert.pem

**Pull request closed without merging**
