### PR TITLE
Release 2.0.9

### PR DESCRIPTION
**Pull request by schlessera**
:warning: **DO NOT MERGE (YET)** :warning:

PR for tracking changes for the 2.0.9 release.

Target release date: **Wednesday November 8th 2023**.

- [x] Check if any dependencies need updating.
- [x] Update the version constant in `src/Requests.php` - PR #xxx.
- [x] Add changelog for the release - PR #xxx
- [ ] Merge this PR.
- [ ] Make sure all CI builds are green.
- [ ] Tag the release against `stable` and push the tag.
- [ ] Review the automatically created PR with the GH Pages docs update.
- [ ] Create a release from the tag (careful, GH defaults to `develop`!) & copy & paste the changelog to it.
    Make sure to copy the links to the issues and the links to the GH usernames from the bottom of the changelog!
- [ ] Merge the GH Pages PR.
    Note: it is important to do this **after** the release as otherwise the information about the latest release
    in the site will not be updated correctly from the GitHub API.
- [ ] Verify that the website regenerated correctly and is in working order.
- [ ] Close the milestone.
- [ ] Open a new milestone for the next release.
- [ ] If any open PRs/issues which were milestoned for the release did not make it into the release, update their milestone.
- [ ] Tweet about the release.
- [ ] Post about it in the WP #core Slack channel.
- [ ] Open a Trac ticket for WordPress Core to update their copy.
- [ ] Submit for "Month in WordPress": https://make.wordpress.org/community/month-in-wordpress-submissions/

### CODE REVIEW

**Comment by jrfnl** [comment]
@schlessera Can you please cherry pick the commit from PR #838 to the `stable` branch and then rebase this PR onto `stable` ?

**Comment by jrfnl** [comment]
The commits related to the other tickets marked as such in #837 should also be cherry picked.

**Comment by schlessera** [comment]
@jrfnl Yes, forget this one, it will be scrapped.

**Comment by schlessera** [comment]
Also, I'll only cherrypick the hotfix, not the other changes, as one of them is sure to cause conflicts downstream.

**Comment by jrfnl** [comment]
@schlessera The GHA one is the important one (aside from the rollback of course) as otherwise we wouldn't be able to get a passing build for the release.

**Pull request closed without merging**
